In [1]:
### 10.11.2025 14:00

In [2]:
import numpy as np

In [3]:
import pickle

In [4]:
!ls

sample_data


In [5]:
!wget https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/classifier.pickle

--2025-11-12 06:48:04--  https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/classifier.pickle
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/refs/heads/main/classifier.pickle [following]
--2025-11-12 06:48:05--  https://raw.githubusercontent.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/refs/heads/main/classifier.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2195 (2.1K) [application/octet-stream]
Saving to: ‘classifier.pickle’

classifier.pi

In [6]:
!ls

classifier.pickle  sample_data


In [7]:
!wget https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/sc.pickle

--2025-11-12 06:48:05--  https://github.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/raw/refs/heads/main/sc.pickle
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/refs/heads/main/sc.pickle [following]
--2025-11-12 06:48:05--  https://raw.githubusercontent.com/Azimovich41/Course-Machine-Learning-Deep-Learning-Model-Deployment/refs/heads/main/sc.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 498 [application/octet-stream]
Saving to: ‘sc.pickle’

sc.pickle           100%[===================>]     49

In [8]:
!ls

classifier.pickle  sample_data	sc.pickle


In [9]:
# 12.11.2025

In [10]:
classifier_colab = pickle.load(open('classifier.pickle', 'rb'))

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.6.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [11]:
#!pip install scikit-learn --upgrade

In [12]:
# !pip install numpy --upgrade

In [13]:
scaler_colab = pickle.load(open('sc.pickle', 'rb'))

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [14]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40, 20000]])))

In [15]:
new_pred

array([0])

In [18]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40, 20000]])))[:, 1]

In [19]:
new_pred_proba

array([0.2])

In [20]:
new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42, 50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42, 50000]])))[:, 1]

In [21]:
new_pred_proba_2

array([0.8])